### PR TITLE
Resolve aliases

### LINKED ISSUE #29: aliases for product and sum types
The following works but I'm required to fully qualify `Rabbitmq.Config.ExchangeType` when referring to that type from `Exchange`. 
```
defmodule Rabbitmq.Config do
  import Algae

  alias __MODULE__.ExchangeType # this doesn't work

  defmodule ExchangeType do
    defsum do
      defdata(Topic :: none())
      defdata(Direct :: none())
      defdata(Fanout :: none())
      defdata(Headers :: none())
    end
  end

  defdata Exchange do
    name :: String.t()
    type :: Rabbitmq.Config.ExchangeType.t()
  end
end
```
Is it possible to alias `ExchangeType` so that I can refer to it without it's namespace in `Exchange`?

### PR DESCRIPTION
**Pull request by icidasset**
Fixes #29 

---

This change allows for the resolving/expanding of aliases.

```elixir
defmodule Simple.NonFlowering.Aquatic.Plant do
  import Algae
  alias __MODULE__

  defmodule Seaweeds do
    defdata ..
  end

  defdata do
    # Before
    a :: Simple.NonFlowering.Aquatic.Plant.Seaweeds.t
    # After
    a :: Plant.Seaweeds.t
  end
end
```

--- 

Notes:
- Weirdly `a :: Plant.Seaweeds.t \\ Plant.Seaweeds.new(..)` does work
- Same goes for `a :: list(Plant.Seaweeds.t)`
- Given the previous notes, I wonder if there's an easier fix without using `Macro.expand`?

:v:

### CODE REVIEW

File: test/algae_dsl_aliasing_test.exs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+defmodule AlgaeDslAliasingTest.Base do
+  import Algae
+
+  alias __MODULE__
+
+  defmodule A do
+    defdata do
+      a :: String.t
```
Comment (expede) [inline test/algae_dsl_aliasing_test.exs]: @icidasset Nitpick: could you add the parens after the `.t`s? That annoying modern syntax and whatnot 🤣

Comment (icidasset) [reply test/algae_dsl_aliasing_test.exs]: @expede Sure thing 👍

**Comment by icidasset** [comment]
I've missed your pr-approval gifs Brooke 😜
